# Generated by Django 5.2.4 on 2025-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В обработке'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='sent', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
