# Generated by Django 5.2.4 on 2025-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_request_options_request_assigned_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cto_comment',
            field=models.TextField(blank=True, help_text='Техническая оценка, видно только менеджеру и КТО', null=True, verbose_name='Комментарий КТО'),
        ),
        migrations.AlterField(
            model_name='request',
            name='manager_comment',
            field=models.TextField(blank=True, help_text='Видно клиенту', null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В обработке'), ('awaiting_tkp', 'Ожидание ТКП'), ('awaiting_approval', 'На согласовании'), ('in_production', 'В производстве'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='sent', max_length=20, verbose_name='Статус'),
        ),
    ]
