# Generated by Django 5.2.4 on 2025-07-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_request_cto_comment_alter_request_manager_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cost_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расчётная стоимость'),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_estimate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сроки поставки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В обработке'), ('awaiting_tkp', 'Ожидание ТКП'), ('awaiting_approval', 'На согласовании'), ('in_production', 'В производстве'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('awaiting_cost', 'Ожидание расчёта стоимости'), ('awaiting_ceo', 'На согласовании у Генерального')], default='sent', max_length=20, verbose_name='Статус'),
        ),
    ]
