# Generated by Django 5.2.4 on 2025-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_request_cost_estimate_request_delivery_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client_approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='request',
            name='client_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Клиент одобрил'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В обработке'), ('awaiting_tkp', 'Ожидание ТКП'), ('awaiting_approval', 'На согласовании'), ('awaiting_cost', 'Ожидание расчёта стоимости'), ('awaiting_ceo', 'На согласовании у Генерального'), ('awaiting_client', 'На согласовании у клиента'), ('in_production', 'В производстве'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='sent', max_length=20, verbose_name='Статус'),
        ),
    ]
