# Generated by Django 5.2.4 on 2025-07-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_request_client_approval_date_request_client_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Договор / Спецификация'),
        ),
        migrations.AddField(
            model_name='request',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Счёт'),
        ),
        migrations.AddField(
            model_name='request',
            name='signed_contract_file',
            field=models.FileField(blank=True, null=True, upload_to='signed_contracts/', verbose_name='Подписанный договор'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В обработке'), ('awaiting_tkp', 'Ожидание ТКП'), ('awaiting_approval', 'На согласовании'), ('awaiting_cost', 'Ожидание расчёта стоимости'), ('awaiting_client', 'На согласовании у клиента'), ('awaiting_ceo', 'На согласовании у Ген.Директора'), ('awaiting_accountant', 'На оформлении счёта'), ('in_production', 'В производстве'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='sent', max_length=20, verbose_name='Статус'),
        ),
    ]
