# Generated by Django 5.2.4 on 2025-07-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_request_contract_file_request_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В обработке'), ('awaiting_tkp', 'Ожидание ТКП'), ('awaiting_approval', 'На согласовании'), ('awaiting_cost', 'Ожидание расчёта стоимости'), ('awaiting_client', 'На согласовании у клиента'), ('awaiting_ceo', 'На согласовании у Ген.Директора'), ('awaiting_accountant', 'На оформлении счёта'), ('awaiting_client_signature', 'На подписание у клиента'), ('signed_by_client', 'Подписано клиентом'), ('in_production', 'В производстве'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='sent', max_length=30, verbose_name='Статус'),
        ),
    ]
