# Generated by Django 5.2.4 on 2025-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client_signed_contract',
            field=models.FileField(blank=True, null=True, upload_to='client_signed_contracts/', verbose_name='Подписанный клиентом договор'),
        ),
        migrations.AddField(
            model_name='request',
            name='client_signed_invoice',
            field=models.FileField(blank=True, null=True, upload_to='client_signed_invoices/', verbose_name='Подписанный клиентом счёт'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В обработке'), ('awaiting_tkp', 'Ожидание ТКП'), ('awaiting_approval', 'На согласовании'), ('awaiting_cost', 'Ожидание расчёта стоимости'), ('awaiting_client', 'На согласовании у клиента'), ('awaiting_documents', 'На оформлении документов'), ('documents_ready', 'Документы готовы'), ('signed_by_client', 'Подписано клиентом'), ('awaiting_client_signature', 'На подписание у клиента'), ('signed_by_client', 'Подписано клиентом'), ('in_production', 'В производстве'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='sent', max_length=30, verbose_name='Статус'),
        ),
    ]
