# Generated by Django 5.2.4 on 2025-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_request_client_signed_shipping_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В обработке'), ('awaiting_tkp', 'Ожидание ТКП'), ('awaiting_approval', 'На согласовании'), ('awaiting_cost', 'Ожидание расчёта стоимости'), ('awaiting_client', 'На согласовании у клиента'), ('awaiting_documents', 'На оформлении документов'), ('documents_ready', 'Документы готовы'), ('awaiting_client_signature', 'На подписание у клиента'), ('signed_by_client', 'Подписано клиентом'), ('in_production', 'В производстве'), ('ready_for_delivery', 'Готова к отгрузке'), ('awaiting_shipping_docs', 'На оформлении отгрузки'), ('shipping_docs_ready', 'Отгрузочные документы готовы'), ('client_signed_shipping', 'Клиент подписал отгрузку'), ('awaiting_payment', 'Ожидание оплаты'), ('payment_confirmed', 'Оплата подтверждена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='sent', max_length=30, verbose_name='Статус'),
        ),
    ]
