# Generated by Django 5.2.4 on 2025-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_request_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль клиента', 'verbose_name_plural': 'Профили клиентов'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='client@example.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='profile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='Профиль заполнен'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
