# Generated by Django 5.2.4 on 2025-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_options_remove_profile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения клиентом'),
        ),
        migrations.AddField(
            model_name='request',
            name='client_response_received',
            field=models.BooleanField(default=False, verbose_name='Ответ от клиента получен'),
        ),
    ]
