# Generated by Django 5.2.4 on 2025-08-15 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход'), ('adjustment', 'Корректировка')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product', verbose_name='Товар')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто внес')),
            ],
            options={
                'verbose_name': 'Запись в журнале склада',
                'verbose_name_plural': 'Журнал склада',
                'ordering': ['-created_at'],
            },
        ),
    ]
