# Generated by Django 4.2.20 on 2025-08-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_inventorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product', verbose_name='Товар со склада'),
        ),
    ]
