# Generated by Django 5.2.4 on 2025-11-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
